export const PERMISSIONS_STORAGE_KEY = "DF_PERMISSIONS"


export const DF_TFJ_PERMISSIONS = "DF_TFJ_PERMISSIONS"
export const DF_MINTRANS_TRANSACTIONS = "DF_MINTRANS_TRANSACTIONS"
export const DF_MINTRANS_SOUSCRIPTIONS = "DF_MINTRANS_SOUSCRIPTIONS"
export const DF_MINTRANS_CREATE_SOUSCRIPTIONS = "DF_MINTRANS_CREATE_SOUSCRIPTIONS"
export const DF_MINTRANS_CASH_IN = "DF_MINTRANS_CASH_IN"
export const DF_MINTRANS_CONFIGS = "DF_MINTRANS_CONFIGS"
export const DF_PARTNER_EDIT = "DF_PARTNER_EDIT"
export const DF_GENERAL_PARAMETERS = "DF_GENERAL_PARAMETERS"
export const DF_CREATE_GENERAL_PARAMETERS = "DF_CREATE_GENERAL_PARAMETERS"
export const APP_PERMISSIONS = [
    DF_TFJ_PERMISSIONS,
    DF_MINTRANS_CASH_IN,
    DF_MINTRANS_TRANSACTIONS,
    DF_MINTRANS_SOUSCRIPTIONS,
    DF_MINTRANS_CREATE_SOUSCRIPTIONS,
    DF_MINTRANS_CONFIGS,
    DF_PARTNER_EDIT,
    DF_GENERAL_PARAMETERS,
    DF_CREATE_GENERAL_PARAMETERS
]